---
title: "hoework_2_krishna"
author: "Krishna"
date: "2024-02-17"
output: html_document
---

```{r}
 
 # Create the data table
dt <- tribble(
  ~x,   ~y,   ~w,   ~z,
  210,   300,   220,   180,
  102,   100,   119,   187,
  176,   175,   188,   173,
  87,   95,   91,   94,
  202,   210,   234,   218,
  110,   122,   131,   128
)

# 1_a: Use map function to find the mean of each column
map_dbl(dt, mean)
```
```{r}
# 1_b: Use map function to find the standard deviation of each column
map_dbl(dt, sd)
```
```{r}
# 1_c: Use map function to calculate the square root of each value of each column
map(dt, sqrt)

```
```{r}
# 1_d: Calculate summary statistics for each column of the dt data table
summary_stats <- data.frame(
  Mean = colMeans(dt),
  Max = apply(dt, 2, max),
  Quartile_1 = apply(dt, 2, quantile, probs = 0.25),
  Quartile_3 = apply(dt, 2, quantile, probs = 0.75),
  Median = apply(dt, 2, median),
  Min = apply(dt, 2, min)
)

# Print the summary statistics
print(summary_stats)
```

```{r}
# Write a function to simulate means from exponential distribution
simulate_means <- function(n_iterations, sample_size) {
  means <- replicate(n_iterations, mean(rexp(sample_size)))
  return(means)
}

# 2_a: Use map function
map_dbl(rep(5, 10000), ~ mean(rexp(.x)))
```        
```{r}
# 2_b: Use replicate function
replicate(10000, mean(rexp(5)))
```

```{r}
# 2_c: Use a for loop to print plots for different sample sizes
sample_sizes <- c(5, 10, 20)
par(mfrow = c(1, length(sample_sizes)))  # Arrange plots in a single row
for (size in sample_sizes) {
  means <- replicate(10000, mean(rexp(size)))
  hist(means, main = paste("Sample size =", size), xlab = "Means", col = "lightblue")
}

```